name: Unit & Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v2
      - name: Iniciar servicios
        run: cd api/ && docker-compose up -d && docker-compose exec -T login /bin/bash -c "pytest test_main.py" || exit 1
      # - name: Correr pruebas
      #   run: docker-compose exec -T login /bin/bash -c "pytest test_main.py" || exit 1
      #   if: always()
      # - name: Verificar pruebas
      #   run: cat test_output.txt
      # - name: Detener servicios
      #   run: docker-compose stop
